Repository jathpr/FE42Bloc3, pull requests merged in 2023-06, with the labels that each got.

#83 feat(hw-41): add dark theme
  my-app/src/App.tsx
  my-app/src/Components/Authorization/Auth.module.css
  my-app/src/Components/Authorization/Auth.tsx
  my-app/src/Components/Header/button.module.css
  my-app/src/Components/Posts/RenderPost.module.css
  my-app/src/Components/Posts/RenderPost.tsx
  my-app/src/Components/Posts/RenderPostsList.tsx
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/Components/Registration/registration.module.css
  my-app/src/Components/Server/auth.ts
  my-app/src/Components/Tabs/Tabs.tsx
  my-app/src/Components/Tabs/tabs.module.css
  my-app/src/Components/ThemeProvider.tsx
  my-app/src/Components/Title/Title.tsx
  my-app/src/Components/Title/title.module.css
  my-app/src/index.tsx
Labels: Ready for review, done

#85 HW47 KaterinaP
  app-hw-37/src/Activate/Activate.tsx
  app-hw-37/src/App.tsx
  app-hw-37/src/Auth/Auth.tsx
  app-hw-37/src/AuthResult/AuthResult.tsx
  app-hw-37/src/AuthResult/authResult.css
  app-hw-37/src/CardsList/CardsList.tsx
  app-hw-37/src/CardsList/card.css
  app-hw-37/src/Navigation/Navigation.tsx
  app-hw-37/src/RegRedirect/RegRedirect.tsx
  app-hw-37/src/Registration/Registration.tsx
  app-hw-37/src/SelectedUser/SelectedUser.tsx
  app-hw-37/src/Store/auth.ts
  app-hw-37/src/Store/post.ts
  app-hw-37/src/getPosts.tsx
  app-hw-37/src/handleAuth.ts
Labels: Ready for review

#84 HW41 Viktar
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.tsx
  my-app/src/Components/Registration/Auth.tsx
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/Components/Search/Search.module.css
  my-app/src/Components/Search/Search.tsx
  my-app/src/Components/SearchProvider.tsx
  my-app/src/Components/Theme/Theme.module.css
  my-app/src/Components/Theme/Theme.tsx
  my-app/src/Components/ThemeProvider.tsx
  my-app/src/HW-38/RenderPost.module.css
  my-app/src/HW-38/RenderPost.tsx
  my-app/src/HW-38/RenderPostList.tsx
  my-app/src/HW-38/posts.ts
  my-app/src/HW_37/BurgerMenu.module.css
  my-app/src/HW_37/BurgerMenu.tsx
  my-app/src/HW_37/Tabs.module.css
  my-app/src/HW_37/Tabs.tsx
  my-app/src/Server/auth.ts
  my-app/src/Title.module.css
  my-app/src/Title.tsx
  my-app/src/index.tsx
  package-lock.json
  package.json
Labels: done

#86 HW40: Hanna
  Hanna/app-hw/my-app/package-lock.json
  Hanna/app-hw/my-app/package.json
  Hanna/app-hw/my-app/src/App.tsx
  Hanna/app-hw/my-app/src/components/Navigation/Navigation.tsx
  Hanna/app-hw/my-app/src/components/PostList/Post/Post.css
  Hanna/app-hw/my-app/src/components/PostList/Posts/Posts.tsx
  Hanna/app-hw/my-app/src/components/PostList/Posts/getPosts.tsx
  Hanna/app-hw/my-app/src/components/Registration/registration.tsx
  Hanna/app-hw/my-app/src/components/SignIn/SignIn.tsx
  Hanna/app-hw/my-app/src/components/Success/Success.tsx
  Hanna/app-hw/my-app/src/components/menu-burger/burger.tsx
  Hanna/app-hw/my-app/src/components/menu-burger/menu.css
  Hanna/app-hw/my-app/src/components/menu-burger/menu.tsx
  Hanna/app-hw/my-app/src/components/tabs/tabs.css
  Hanna/app-hw/my-app/src/components/tabs/tabs.tsx
  Hanna/app-hw/my-app/src/components/title/title.css
  Hanna/app-hw/my-app/src/components/title/title.tsx
  Hanna/app-hw/my-app/src/index.tsx
Labels: Ready for review
