Repository jathpr/FE42Bloc3, pull requests merged in 2023-04, with the labels that each got.

#3 Polina HW 33
  hw-33.js
Labels: Ready for review

#1 HW1 Maria
  app.js
Labels: Ready for review

#2 HW33 KaterinaP
  hw_33.js
Labels: enhancement

#4 HW-33_Yury
  hw_33.js
  index.html
Labels: Ready for review

#8 HW-34_Yury
  .gitignore
  Homework_34.md
  hw-34.js
  hw-34.ts
  lesson_34.md
Labels: Ready for review

#5 HW2 Maria
  .gitignore
  hw_2.js
  hw_2.ts
  package-lock.json
  package.json
Labels: done

#7 HW34 KaterinaP
  .gitignore
  Homework_34.md
  hw_34.js
  hw_34.ts
  lesson_34.md
  package-lock.json
  package.json
Labels: done

#9 HW33 Aliaksandr
  hw-33.js
Labels: Ready for review

#10 HW34 Aliaksandr
  34.ts
Labels: Ready for review

#12 Olga hw 33
  hw-33.js
Labels: Ready for review

#13 HW33 Rustam & Vadim
  hw33/index.html
  hw33/script.js
Labels: Ready for review

#14 HW34 Vadim&Rustam
  HW34/testts.ts
Labels: Ready for review

#15 Olga hw 34
  .gitignore
  package-lock.json
  package.json
  typescript-hw34.js
  typescript-hw34.ts
Labels: Ready for review

#18 HW3 Maria
  hw_3.js
  hw_3.ts
  package-lock.json
  package.json
Labels: enhancement, Ready for review

#19 HW-35_Yury
  .gitignore
  Homework_35.md
  Lesson_35.md
  hw-35.js
  hw-35.ts
  package-lock.json
  package.json
Labels: Ready for review

#22 HW35 KaterinaP
  Homework_35.md
  hw_35.js
  hw_35.ts
Labels: Ready for review

#28 HW33 Hanna
  Hanna/hw33_Hanna/index.html
  Hanna/hw33_Hanna/main.js
  Hanna/hw33_Hanna/main.ts
Labels: Ready for review

#27 HW4 Maria
  hw_4.js
  hw_4.ts
Labels: Ready for review

#32 HW36 Aliaksandr
  hw-36.js
  hw-36.ts
Labels: Ready for review

#33 HW 36 Polina
  hw-36.js
  hw-36.ts
Labels: Ready for review

#24 HW 35 Polina
  hw-35.js
  hw-35.ts
  package-lock.json
  package.json
Labels: Ready for review

#11 Viktar-HW_34
  .gitignore
  hw-34.js
  hw-34.ts
Labels: enhancement, Ready for review

#25 HW35 Aliaksandr
  hw-35.js
  hw-35.ts
  package-lock.json
  package.json
Labels: enhancement, Ready for review

#36 HW 36 KaterinaP
  Homework 36.pdf
  Homework_36.md
  hw_36.js
  hw_36.ts
  package-lock.json
  package.json
Labels: Ready for review

#40 Olga hw 37
  my-app/src/App.tsx
  my-app/src/Button/Button.tsx
  my-app/src/Button/ButtonClass.tsx
  my-app/src/Button/button.module.css
  my-app/src/Tabs/Tabs.tsx
  my-app/src/Tabs/tabs.module.css
  my-app/src/Title.tsx
  my-app/src/index.tsx
  my-app/src/title.module.css
Labels: Ready for review

#39 HW37 KaterinaP
  Homework 37.pdf
  app-hw-37/.gitignore
  app-hw-37/README.md
  app-hw-37/package-lock.json
  app-hw-37/package.json
  app-hw-37/public/favicon.ico
  app-hw-37/public/index.html
  app-hw-37/public/manifest.json
  app-hw-37/public/robots.txt
  app-hw-37/src/App.test.tsx
  app-hw-37/src/App.tsx
  app-hw-37/src/components/Burger.tsx
  app-hw-37/src/components/Container.tsx
  app-hw-37/src/components/Menu.tsx
  app-hw-37/src/components/SelectUserMenu.tsx
  app-hw-37/src/components/Tabs.tsx
  app-hw-37/src/components/TaskNum.tsx
  app-hw-37/src/components/Title.tsx
  app-hw-37/src/components/Wrapper.tsx
  app-hw-37/src/index.tsx
  app-hw-37/src/react-app-env.d.ts
  app-hw-37/src/reportWebVitals.ts
  app-hw-37/src/setupTests.ts
  app-hw-37/src/styles/Title.css
  app-hw-37/src/styles/burger.css
  app-hw-37/src/styles/index.css
  app-hw-37/src/styles/menu.css
  app-hw-37/src/styles/selectUserMenu.css
  app-hw-37/src/styles/tabs.css
  app-hw-37/tsconfig.json
Labels: Ready for review

#41 HW37 Viktar
  my-app/src/App.test.tsx
  my-app/src/App.tsx
  my-app/src/Auth.tsx
  my-app/src/HW_37/BurgerMenu.module.css
  my-app/src/HW_37/BurgerMenu.tsx
  my-app/src/HW_37/Tabs.module.css
  my-app/src/HW_37/Tabs.tsx
  my-app/src/Title.module.css
  my-app/src/Title.tsx
  my-app/src/index.tsx
Labels: Ready for review

#44 HW38 KaterinaP
  Homework 38.pdf
  app-hw-37/public/index.html
  app-hw-37/src/App.tsx
  app-hw-37/src/hw37/Tabs/tabs.css
  app-hw-37/src/hw38/CardsList/Card.tsx
  app-hw-37/src/hw38/CardsList/CardsList.tsx
  app-hw-37/src/hw38/CardsList/card.css
  app-hw-37/src/hw38/PostCard/PostCard.tsx
  app-hw-37/src/hw38/PostCard/postCard.css
  app-hw-37/src/index.css
Labels: enhancement

#34 HW 36 Yury
  Homework 36.pdf
  Homework_36.md
  Lesson 36. На занятии.pdf
  hw_36.js
  hw_36.ts
  lesson_36.md
  package-lock.json
  package.json
Labels: Ready for review, done

#37 HW 37 Yury
  react/my-app/.gitignore
  react/my-app/README.md
  react/my-app/package-lock.json
  react/my-app/package.json
  react/my-app/public/favicon.ico
  react/my-app/public/index.html
  react/my-app/public/logo192.png
  react/my-app/public/logo512.png
  react/my-app/public/manifest.json
  react/my-app/public/robots.txt
  react/my-app/src/App.css
  react/my-app/src/App.test.tsx
  react/my-app/src/App.tsx
  react/my-app/src/hw_37/ButtonHeader.tsx
  react/my-app/src/hw_37/Tabs.tsx
  react/my-app/src/hw_37/body.tsx
  react/my-app/src/hw_37/header.tsx
  react/my-app/src/hw_37/wrapper.tsx
  react/my-app/src/index.css
  react/my-app/src/index.tsx
  react/my-app/src/logo.svg
  react/my-app/src/react-app-env.d.ts
  react/my-app/src/reportWebVitals.ts
  react/my-app/src/setupTests.ts
  react/my-app/tsconfig.json
Labels: Ready for review

#45 HW38 Polina
  my-app/src/App.tsx
  my-app/src/HW37/hw-37.tsx
  my-app/src/HW38/Hw-38.tsx
  my-app/src/HW38/Post.css
  my-app/src/HW38/Post.tsx
  my-app/src/HW38/PostsList.tsx
  my-app/src/Lessons/Lesson3/PostsLesson3.tsx
  my-app/src/Lessons/Lesson3/PostsListLesson3.tsx
  my-app/src/index.tsx
Labels: Ready for review, done

#46 HW39 KaterinaP
  app-hw-37/public/index.html
  app-hw-37/src/App.tsx
  app-hw-37/src/hw37/Title/Title.css
  app-hw-37/src/hw37/Title/Title.tsx
  app-hw-37/src/hw38/CardsList/Card.tsx
  app-hw-37/src/hw38/CardsList/CardsList.tsx
  app-hw-37/src/hw38/CardsList/card.css
  app-hw-37/src/hw38/PostCard/PostCard.tsx
  app-hw-37/src/hw38/PostCard/postCard.css
  app-hw-37/src/hw39/Auth/Auth.tsx
  app-hw-37/src/hw39/Auth/auth.css
  app-hw-37/src/hw39/Navigation/Navigation.tsx
  app-hw-37/src/hw39/Reg/Reg.tsx
  app-hw-37/src/hw39/Reg/reg.css
  app-hw-37/src/index.css
Labels: Ready for review, done

#48 HW 38 Yury
  react/my-app/src/hw_37/body.tsx
  react/my-app/src/hw_38/CardPost.tsx
  react/my-app/src/hw_38/Posts.tsx
  react/my-app/src/hw_38/PostsWrapper.tsx
  react/my-app/src/hw_38/cards.css
  react/my-app/src/index.css
Labels: done

#47 HW5 Maria
  my-app/README.md
  my-app/close-cross-svgrepo-com.svg
  my-app/menu-hamburger-svgrepo-com.svg
  my-app/package-lock.json
  my-app/package.json
  my-app/public/favicon.ico
  my-app/public/index.html
  my-app/public/manifest.json
  my-app/public/robots.txt
  my-app/src/App.tsx
  my-app/src/HW5/ButtonHamburger.tsx
  my-app/src/HW5/Tabs.tsx
  my-app/src/HW5/Title.tsx
  my-app/src/HW5/User.tsx
  my-app/src/HW5/css/ButtonHamburger.module.css
  my-app/src/HW5/css/Tabs.module.css
  my-app/src/HW5/css/Title.module.css
  my-app/src/HW5/css/User.module.css
  my-app/src/index.tsx
  my-app/src/react-app-env.d.ts
  my-app/tsconfig.json
Labels: Ready for review

#49 HW6 Maria
  .gitignore
  my-app/public/index.html
  my-app/src/App.tsx
  my-app/src/HW5/css/ButtonHamburger.module.css
  my-app/src/HW5/css/Title.module.css
  my-app/src/HW6/Post.tsx
  my-app/src/HW6/PostsList.tsx
  my-app/src/HW6/css/Post.module.css
  my-app/src/HW6/css/PostsList.module.css
Labels: enhancement, done

#52 Olga hw 38
  my-app/src/App.tsx
  my-app/src/Button/ButtonClass.tsx
  my-app/src/hw-38/RenderPost.module.css
  my-app/src/hw-38/RenderPost.tsx
  my-app/src/hw-38/RenderPostsList.tsx
  my-app/src/hw-38/posts.ts
  package-lock.json
  package.json
Labels: enhancement, Ready for review, done

#55 HW38-Viktar
  Homework 38.pdf
  Homework 39.pdf
  Lesson 38. На занятии.pdf
  Lesson 39. На занятии.pdf
  my-app/src/App.tsx
  my-app/src/HW-38/Posts.tsx
  my-app/src/HW-38/RenderPost.module.css
  my-app/src/HW-38/RenderPost.tsx
  my-app/src/HW-38/RenderPostList.tsx
  my-app/src/HW_37/BurgerMenu.tsx
Labels: Ready for review
