Repository jathpr/FE42Bloc3, pull requests merged in 2023-05, with the labels that each got.

#56 HW40 KaterinaP
  app-hw-37/public/index.html
  app-hw-37/src/App.tsx
  app-hw-37/src/Auth/Auth.tsx
  app-hw-37/src/CardsList/Card.tsx
  app-hw-37/src/CardsList/CardsList.tsx
  app-hw-37/src/FullScreenCard/FullScreenCard.tsx
  app-hw-37/src/FullScreenCard/fullScreenCard.css
  app-hw-37/src/Main/Main.tsx
  app-hw-37/src/Navigation/Navigation.tsx
  app-hw-37/src/PostCard/PostCard.tsx
  app-hw-37/src/Reg/Reg.tsx
  app-hw-37/src/getPosts.tsx
Labels: done

#59 HW 40 Polina
  my-app/public/index.html
  my-app/public/logo192.png
  my-app/public/logo512.png
  my-app/public/manifest.json
  my-app/public/robots.txt
  my-app/src/App.css
  my-app/src/App.tsx
  my-app/src/Components/Authorization/Authorization.css
  my-app/src/Components/Authorization/Authorization.tsx
  my-app/src/Components/Button/ButtonBurger.module.css
  my-app/src/Components/Post/Posts.css
  my-app/src/Components/Post/PostsList.tsx
  my-app/src/Components/Post/RenderPost.tsx
  my-app/src/Components/Registration/Registration.css
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/Components/Title/Title.css
  my-app/src/Components/Title/Title.tsx
  my-app/src/Components/getPosts.ts
  my-app/src/Lessons/Navigation.tsx
  my-app/src/Lessons/Registration.tsx
  my-app/src/Lessons/languageContext.ts
  my-app/src/index.tsx
Labels: Ready for review

#60 HW 40 Yury
  react/my-app/src/hw_37/body.tsx
  react/my-app/src/hw_37/header.tsx
  react/my-app/src/hw_37/wrapper.tsx
  react/my-app/src/hw_40/Auth.tsx
  react/my-app/src/hw_40/auth.css
  react/my-app/src/index.css
Labels: Ready for review

#61 HW37 Hanna
  Hanna/app-hw/app.tsx
  Hanna/app-hw/hw37/title/title.css
  Hanna/app-hw/hw37/title/title.tsx
  Hanna/app-hw/index.css
  Hanna/app-hw/index.tsx
  Hanna/app-hw/my-app/.gitignore
  Hanna/app-hw/my-app/README.md
  Hanna/app-hw/my-app/package-lock.json
  Hanna/app-hw/my-app/package.json
  Hanna/app-hw/my-app/public/index.html
  Hanna/app-hw/my-app/src/App.tsx
  Hanna/app-hw/my-app/src/hw37/menu-burger/burger.tsx
  Hanna/app-hw/my-app/src/hw37/menu-burger/menu.css
  Hanna/app-hw/my-app/src/hw37/menu-burger/menu.tsx
  Hanna/app-hw/my-app/src/hw37/tabs/tabs.css
  Hanna/app-hw/my-app/src/hw37/tabs/tabs.tsx
  Hanna/app-hw/my-app/src/hw37/title/title.css
  Hanna/app-hw/my-app/src/hw37/title/title.tsx
  Hanna/app-hw/my-app/src/img/Hamburger_icon.svg.png
  Hanna/app-hw/my-app/src/img/close.png
  Hanna/app-hw/my-app/src/img/profile_picture.jpg
  Hanna/app-hw/my-app/src/img/search.svg
  Hanna/app-hw/my-app/src/index.css
  Hanna/app-hw/my-app/src/index.tsx
  Hanna/app-hw/my-app/src/react-app-env.d.ts
  Hanna/app-hw/my-app/tsconfig.json
Labels: Ready for review

#58 HW7 Maria
  .gitignore
  my-app/public/favicon.ico
  my-app/public/manifest.json
  my-app/public/robots.txt
  my-app/src/App.tsx
  my-app/src/Components/Auth.tsx
  my-app/src/Components/ButtonHamburger.tsx
  my-app/src/Components/Header.tsx
  my-app/src/Components/Navigation.tsx
  my-app/src/Components/Post.tsx
  my-app/src/Components/PostPage.tsx
  my-app/src/Components/PostsList.tsx
  my-app/src/Components/Registration.tsx
  my-app/src/Components/Search.tsx
  my-app/src/Components/Tabs.tsx
  my-app/src/Components/Title.tsx
  my-app/src/Components/User.tsx
  my-app/src/HW5/ButtonHamburger.tsx
  my-app/src/HW5/User.tsx
  my-app/src/HW5/css/User.module.css
  my-app/src/HW6/PostsList.tsx
  my-app/src/css/Auth.module.css
  my-app/src/css/ButtonHamburger.module.css
  my-app/src/css/Header.module.css
  my-app/src/css/Navigation.module.css
  my-app/src/css/Post.module.css
  my-app/src/css/PostPage.module.css
  my-app/src/css/PostsList.module.css
  my-app/src/css/Registration.module.css
  my-app/src/css/Search.module.css
  my-app/src/css/Tabs.module.css
  my-app/src/css/Title.module.css
  my-app/src/css/User.module.css
  my-app/src/icons/close-cross-svgrepo-com.svg
  my-app/src/icons/menu-hamburger-svgrepo-com.svg
  my-app/src/icons/user-svgrepo-com.svg
  my-app/src/server/User.ts
  my-app/src/server/getPosts.ts
Labels: Ready for review

#64 HW41 KaterinaP
  app-hw-37/src/App.tsx
  app-hw-37/src/Auth/Auth.tsx
  app-hw-37/src/CardsList/Card.tsx
  app-hw-37/src/CardsList/CardsList.tsx
  app-hw-37/src/FullScreenCard/FullScreenCard.tsx
  app-hw-37/src/Main/Main.tsx
  app-hw-37/src/Menu/Menu.tsx
  app-hw-37/src/Menu/MenuInput.tsx
  app-hw-37/src/Menu/ThemeBtn.tsx
  app-hw-37/src/Menu/menu.css
  app-hw-37/src/Navigation/Navigation.tsx
  app-hw-37/src/Reg/Reg.tsx
  app-hw-37/src/ThemeContext.ts
  app-hw-37/src/Title/Title.css
  app-hw-37/src/Title/Title.tsx
  app-hw-37/src/getPosts.tsx
  app-hw-37/src/index.css
  app-hw-37/tsconfig.json
Labels: question, Ready for review

#68 HW8 Maria
  my-app/src/Components/Auth.tsx
  my-app/src/Components/Navigation.tsx
  my-app/src/Components/Post.tsx
  my-app/src/Components/PostPage.tsx
  my-app/src/Components/PostsList.tsx
  my-app/src/Components/Registration.tsx
  my-app/src/Components/Search.tsx
  my-app/src/css/Auth.module.css
  my-app/src/css/Registration.module.css
Labels: Ready for review

#72 HW37 Aliaksandr
  hw_37/README.md
  hw_37/package-lock.json
  hw_37/package.json
  hw_37/public/favicon.ico
  hw_37/public/index.html
  hw_37/public/logo192.png
  hw_37/public/logo512.png
  hw_37/public/manifest.json
  hw_37/public/robots.txt
  hw_37/src/App.test.tsx
  hw_37/src/App.tsx
  hw_37/src/Burger.tsx
  hw_37/src/Menu.tsx
  hw_37/src/Tabs.tsx
  hw_37/src/Title.tsx
  hw_37/src/css/app.css
  hw_37/src/css/index.css
  hw_37/src/css/menu.css
  hw_37/src/css/selectMenu.css
  hw_37/src/css/tabs.css
  hw_37/src/css/title.css
  hw_37/src/index.tsx
  hw_37/src/react-app-env.d.ts
  hw_37/src/reportWebVitals.ts
  hw_37/src/setupTests.ts
  hw_37/tsconfig.json
Labels: Ready for review

#73 HW42 KaterinaP
  app-hw-37/package-lock.json
  app-hw-37/package.json
  app-hw-37/public/index.html
  app-hw-37/src/App.tsx
  app-hw-37/src/Auth/Auth.tsx
  app-hw-37/src/CardsList/CardsList.tsx
  app-hw-37/src/CardsList/card.css
  app-hw-37/src/FullScreenCard/FullScreenCard.tsx
  app-hw-37/src/Header/Header.tsx
  app-hw-37/src/Header/dark-btn.svg
  app-hw-37/src/Header/header.css
  app-hw-37/src/Header/light-btn.svg
  app-hw-37/src/Main/Main.tsx
  app-hw-37/src/Menu/Menu.tsx
  app-hw-37/src/Menu/ThemeBtn.tsx
  app-hw-37/src/Menu/menu.css
  app-hw-37/src/Navigation/Navigation.tsx
  app-hw-37/src/Reg/Reg.tsx
  app-hw-37/src/SelectUserMenu/SelectUserMenu.tsx
  app-hw-37/src/SelectUserMenu/selectUserMenu.css
  app-hw-37/src/SelectedUser/SelectedUser.tsx
  app-hw-37/src/SelectedUser/selectedUser.css
  app-hw-37/src/ThemeContext.ts
  app-hw-37/src/getPosts.tsx
  app-hw-37/src/index.css
  app-hw-37/src/index.tsx
  package-lock.json
  package.json
Labels: Ready for review

#69 Revert "HW 41 Polina"
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.tsx
  my-app/src/Components/Authorization/Authorization.css
  my-app/src/Components/Authorization/Authorization.tsx
  my-app/src/Components/Post/PostsList.tsx
  my-app/src/Components/Post/RenderPost.tsx
  my-app/src/Components/Post/getPosts.ts
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/index.tsx
Labels: done

#77 HW 42 Polina
  my-app/package-lock.json
  my-app/package.json
  my-app/public/favicon.ico
  my-app/src/App.css
  my-app/src/App.tsx
  my-app/src/AppWrapper.tsx
  my-app/src/Components/Authorization/Authorization.tsx
  my-app/src/Components/BurgerMenu/ButtonBurger.tsx
  my-app/src/Components/BurgerMenu/Menu.css
  my-app/src/Components/BurgerMenu/Menu.tsx
  my-app/src/Components/Context/themeContext.ts
  my-app/src/Components/Navigation/Navigation.tsx
  my-app/src/Components/Post/OnePost.css
  my-app/src/Components/Post/OnePost.tsx
  my-app/src/Components/Post/Posts.css
  my-app/src/Components/Post/PostsList.tsx
  my-app/src/Components/Post/RenderPost.tsx
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/Components/Search/Search.css
  my-app/src/Components/Search/Search.tsx
  my-app/src/Components/Search/magicGlass.svg
  my-app/src/Components/ThemeButton/ThemeButton.css
  my-app/src/Components/ThemeButton/ThemeButton.tsx
  my-app/src/Components/ThemeButton/moon.svg
  my-app/src/Components/ThemeButton/sun.svg
  my-app/src/Components/Title/Title.css
  my-app/src/Components/Title/Title.tsx
  my-app/src/Components/User/User.css
  my-app/src/Components/User/User.tsx
  my-app/src/Components/User/userIcon.svg
  my-app/src/Store/post.ts
  my-app/src/Store/store.ts
  my-app/src/index.tsx
Labels: Ready for review

#78 HW43 KaterinaP
  app-hw-37/package-lock.json
  app-hw-37/package.json
  app-hw-37/src/App.tsx
  app-hw-37/src/Auth/Auth.tsx
  app-hw-37/src/Burger/Burger.tsx
  app-hw-37/src/CardsList/Card.tsx
  app-hw-37/src/CardsList/CardsList.tsx
  app-hw-37/src/FullScreenCard/FullScreenCard.tsx
  app-hw-37/src/FullScreenImg/FullScreanImg.tsx
  app-hw-37/src/FullScreenImg/fullScreenImg.css
  app-hw-37/src/Header/Header.tsx
  app-hw-37/src/Main/Main.tsx
  app-hw-37/src/Menu/MagnGlass.svg
  app-hw-37/src/Menu/Menu.tsx
  app-hw-37/src/Menu/MenuInput.tsx
  app-hw-37/src/Navigation/Navigation.tsx
  app-hw-37/src/Reg/Reg.tsx
  app-hw-37/src/SelectedUser/SelectedUser.tsx
  app-hw-37/src/Store/auth.ts
  app-hw-37/src/Store/images.ts
  app-hw-37/src/Store/post.ts
  app-hw-37/src/Store/search.ts
  app-hw-37/src/Store/store.ts
  app-hw-37/src/Store/theme.ts
  app-hw-37/src/Title/Title.tsx
  app-hw-37/src/getPosts.tsx
  app-hw-37/src/index.tsx
Labels: Ready for review

#65 HW 41 Yury
  react/my-app/src/App.tsx
  react/my-app/src/components/Auth.tsx
  react/my-app/src/components/Body.tsx
  react/my-app/src/components/ButtonHeader.tsx
  react/my-app/src/components/CardPost.tsx
  react/my-app/src/components/CardsWrapper.tsx
  react/my-app/src/components/CheckTheme.tsx
  react/my-app/src/components/Header.tsx
  react/my-app/src/components/Posts.tsx
  react/my-app/src/components/Reg.tsx
  react/my-app/src/components/Registration.tsx
  react/my-app/src/components/Search.tsx
  react/my-app/src/components/Title.tsx
  react/my-app/src/components/wrapper.tsx
  react/my-app/src/hw_37/Tabs.tsx
  react/my-app/src/hw_37/body.tsx
  react/my-app/src/hw_37/header.tsx
  react/my-app/src/hw_37/wrapper.tsx
  react/my-app/src/hw_38/Posts.tsx
  react/my-app/src/images/header__search.png
  react/my-app/src/index.css
  react/my-app/src/index.tsx
  react/my-app/src/styles/auth.css
  react/my-app/src/styles/checkTheme.css
  react/my-app/src/styles/header.css
  react/my-app/src/styles/post.css
  react/my-app/src/styles/reg.css
  react/my-app/src/styles/search.css
  react/my-app/src/tools/Counter.tsx
  react/my-app/src/tools/getPosts.ts
  react/my-app/src/tools/languageContext.ts
  react/my-app/src/tools/themeContext.ts
Labels: done

#74 HW39 Hanna
  Hanna/app-hw/my-app/src/App.tsx
  Hanna/app-hw/my-app/src/hw38/PostList/Post/Post.css
  Hanna/app-hw/my-app/src/hw38/PostList/Post/Post.tsx
  Hanna/app-hw/my-app/src/hw38/PostList/Posts/PostList.tsx
  Hanna/app-hw/my-app/src/hw38/PostList/Posts/Posts.tsx
  Hanna/app-hw/my-app/src/hw38/PostList/Posts/getPosts.tsx
  Hanna/app-hw/my-app/src/hw39/Navigation/Navigation.tsx
  Hanna/app-hw/my-app/src/hw39/SignIn/SignIn.tsx
  Hanna/app-hw/my-app/src/hw39/Success/Success.tsx
Labels: enhancement, help wanted, Ready for review

#75 HW10 Maria
  my-app/src/Components/Auth.tsx
  my-app/src/Components/ButtonHamburger.tsx
  my-app/src/Components/Header.tsx
  my-app/src/Components/Menu.tsx
  my-app/src/Components/Navigation.tsx
  my-app/src/Components/PostPage.tsx
  my-app/src/Components/PostsList.tsx
  my-app/src/Components/Registration.tsx
  my-app/src/Components/Search.tsx
  my-app/src/Components/User.tsx
  my-app/src/css/Header.module.css
  my-app/src/css/Menu.module.css
  my-app/src/css/User.module.css
  my-app/src/icons/moon-svgrepo-com.svg
  my-app/src/icons/sun-svgrepo-com.svg
  my-app/src/index.tsx
  my-app/src/server/getPosts.ts
  package-lock.json
  package.json
Labels: enhancement, done

#76 HW38 Aliaksandr
  hw_38/README.md
  hw_38/package-lock.json
  hw_38/package.json
  hw_38/public/favicon.ico
  hw_38/public/index.html
  hw_38/public/logo192.png
  hw_38/public/logo512.png
  hw_38/public/manifest.json
  hw_38/public/robots.txt
  hw_38/src/App.test.tsx
  hw_38/src/App.tsx
  hw_38/src/Card.tsx
  hw_38/src/PostCards.tsx
  hw_38/src/PostsList.tsx
  hw_38/src/css/app.css
  hw_38/src/css/index.css
  hw_38/src/css/postCards.css
  hw_38/src/css/postsList.css
  hw_38/src/index.tsx
  hw_38/src/react-app-env.d.ts
  hw_38/src/reportWebVitals.ts
  hw_38/src/setupTests.ts
  hw_38/tsconfig.json
Labels: enhancement, done

#79 HW 44 Polina
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.css
  my-app/src/App.tsx
  my-app/src/Components/AddToFavorites/AddToFavorites.css
  my-app/src/Components/AddToFavorites/AddToFavorites.tsx
  my-app/src/Components/AddToFavorites/bookmark.svg
  my-app/src/Components/Authorization/Authorization.tsx
  my-app/src/Components/Likes/Likes.css
  my-app/src/Components/Likes/Likes.tsx
  my-app/src/Components/Likes/dislike.svg
  my-app/src/Components/Likes/like.svg
  my-app/src/Components/Navigation/Navigation.tsx
  my-app/src/Components/Post/OnePost.tsx
  my-app/src/Components/Post/PostsList.css
  my-app/src/Components/Post/PostsList.tsx
  my-app/src/Components/Post/RenderPost.css
  my-app/src/Components/Post/RenderPost.tsx
  my-app/src/Components/Post/getPosts.ts
  my-app/src/Components/Registration/Registration.tsx
  my-app/src/Components/Search/Search.tsx
  my-app/src/Components/Tabs/AllTabs.tsx
  my-app/src/Components/Tabs/FavoritePosts.tsx
  my-app/src/Components/Tabs/Tabs.css
  my-app/src/Components/Tabs/Tabs.tsx
  my-app/src/Components/Title/Title.tsx
  my-app/src/Lessons/Counter.tsx
  my-app/src/Store/post.ts
  my-app/src/index.tsx
  my-app/tsconfig.json
  package-lock.json
  package.json
Labels: help wanted, Ready for review
